version: "3.8"
services:
  frontend:
    build: ./frontend
    image: frontend
    environment:
      - PORT=8080
      - AUTH_API_ADDRESS=http://auth-api:8000
      - TODOS_API_ADDRESS=http://todos-api:8082
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    ports:
      - 8080:8080
    depends_on:
      - auth-api
      - users-api
      - todos-api
      - redis
      - zipkin
  auth-api:
    build: ./auth-api
    image: auth-api
    environment:
      - AUTH_API_PORT=8000
      - JWT_SECRET=PRFT
      - USERS_API_ADDRESS=http://users-api:8083
  todos-api:
    build: ./todos-api
    image: todos-api
    environment:
      - TODO_API_PORT=8082
      - JWT_SECET=PRFT
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - auth-api
      - zipkin
      - redis
  users-api:
    build: ./users-api
    image: users-api
    environment:
      - SERVERT_PORT=8083
      - JWT_SECRET=PRFT
    depends_on:
      - auth-api
  log-message-processor:
    build: ./log-message-processor
    image: log-message-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis
  redis:
    image: redis:alpine
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411





  